PersonalFinance/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path("",include("accounts.urls")),
    path('admin/', admin.site.urls),
    # path("", include("authentication.urls")),  # add this
    path("accountbook/", include("accountbook.urls")),  # add this
    path("property/", include("property.urls")),  # add this
    path("dashboard/", include("dashboard.urls")),  # add this
    path("consumptionANDincome/",include("consumptionANDincome.urls")),
    #path("accounts/",include("accounts.urls"))
    # path("", include("app.urls"))  # add this
    
]

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('send_code/', views.send_code_view, name='send_code'),  # 新增发送验证码的路由
    path('forgot_password/', views.forgot_password_view, name='forgot_password'),  # 忘记密码页面
    path('verify_code/', views.verify_code_view, name='verify_code'),  # 验证码验证页面
    path('reset_password/', views.reset_password_view, name='reset_password'),  # 重置密码页面
    path('profile/', views.profile_view, name='profile'),#个人资料页面
    path('settings/', views.settings_view, name='settings'),
    path('settings/change_password/', views.change_password, name='change_password'),
    path('logout/', views.logout_view, name='logout'),

]

consumptionANDincome/urls.py
from django.urls import path, re_path
from . import views
app_name = 'consumptionANDincome'

urlpatterns = [
    # 收入统计页面
    path('', views.income_list, name='income_list'),
    path('income_statistic/', views.income_statistic, name='income_statistic'),
    # 支出统计页面
    path('consumption_statistic/', views.consumption_statistic, name='consumption_statistic'),
    # 结余统计页面
    path('surplus_statistic/', views.surplus_statistic, name='surplus_statistic'),
    # 添加收入条目
    path('add_income/', views.add_income, name='add_income'),
    # 删除收入条目
    path('delete_income/<int:income_id>/', views.delete_income, name='delete_income'),
    # 更新收入条目
    path('update_income/<int:income_id>/', views.update_income, name='update_income'),
    
    # 添加支出条目
    path('add_expense/', views.add_expense, name='add_expense'),
    # 删除支出条目
    path('delete_expense/<int:expense_id>/', views.delete_expense, name='delete_expense'),
    # 更新支出条目
    path('update_expense/<int:expense_id>/', views.update_expense, name='update_expense'),
    path('expenseincome/', views.expenseincome_list, name='expenseincome_list'),
    path('income/', views.income_list, name='income_list'),
    path('expense/', views.expense_list, name='expense_list'),
    path('weekly-income-by-category/', views.weekly_income_by_category, name='weekly_income_by_category'),
    path('weekly-expenses-by-category/', views.weekly_expenses_by_category, name='weekly_expenses_by_category'),
    path('expenses-by-category/', views.expenses_by_category_in_interval, name='expenses_by_category_in_interval'),
    path('income-by-category/', views.income_by_category_in_interval, name='income_by_category_in_interval'),
]

consumptionANDincome/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

from accountbook.models import FundAccount, AccountBook  # 导入 FundAccount 和 AccountBook 模型

class ExpenseEntry(models.Model):
    # 支出种类选项
    EXPENSE_CATEGORIES = [
        ('food', 'Food'),
        ('transport', 'Transport'),
        ('entertainment', 'Entertainment'),
        ('shopping', 'Shopping'),
        ('utilities', 'Utilities'),
        ('others', 'Others'),
    ]
    
    # 货币种类选项
    CURRENCIES = [
        ('CNY', 'CNY'),
        ('USD', 'USD'),
        ('EUR', 'EUR'),
        ('JPY', 'JPY'),
        ('GBP', 'GBP'),
        ('other', 'Other'),
    ]
    
    expense_id = models.AutoField(primary_key=True)  # 支出条目ID，自动生成
    expense_category = models.CharField(
        max_length=50,
        choices=EXPENSE_CATEGORIES,
        default='others'
    )  # 支出种类，使用 choices 限制选择
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # 支出金额
    currency = models.CharField(
        max_length=10,
        choices=CURRENCIES,
        default='CNY'
    )  # 货币种类，使用 choices 限制选择
    expense_time = models.DateTimeField()  # 支出时间
    include_in_balance = models.BooleanField(default=False)  # 是否计入收支
    include_in_budget = models.BooleanField(default=False)  # 是否计入预算
    reimbursement = models.BooleanField(default=False)  # 是否报销
    account = models.ForeignKey(FundAccount, related_name='expense_entries', on_delete=models.CASCADE)  # 选择账户ID
    account_book = models.ForeignKey(AccountBook, related_name='expense_entries', on_delete=models.CASCADE)  # 记录账本ID
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    def __str__(self):
        return f"Expense Entry {self.expense_id} - {self.get_expense_category_display()}"

class IncomeEntry(models.Model):
    # 收入种类选项
    INCOME_CATEGORIES = [
        ('salary', 'Salary'),
        ('investment', 'Investment'),
        ('business', 'Business'),
        ('gift', 'Gift'),
        ('others', 'Others'),
    ]
    
    # 货币种类选项
    CURRENCIES = [
        ('CNY', 'CNY'),
        ('USD', 'USD'),
        ('EUR', 'EUR'),
        ('JPY', 'JPY'),
        ('GBP', 'GBP'),
        ('other', 'Other'),
    ]
    
    income_id = models.AutoField(primary_key=True)  # 收入条目ID，自动生成
    income_category = models.CharField(
        max_length=50,
        choices=INCOME_CATEGORIES,
        default='others'
    )  # 收入种类，使用 choices 限制选择
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # 收入金额
    currency = models.CharField(
        max_length=10,
        choices=CURRENCIES,
        default='CNY'
    )  # 货币种类，使用 choices 限制选择
    income_time = models.DateTimeField()  # 收入时间
    include_in_balance = models.BooleanField(default=False)  # 是否计入收支
    account = models.ForeignKey(FundAccount, related_name='income_entries', on_delete=models.CASCADE)  # 选择账户ID
    account_book = models.ForeignKey(AccountBook, related_name='income_entries', on_delete=models.CASCADE)  # 记录账本ID
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    def __str__(self):
        return f"Income Entry {self.income_id} - {self.get_income_category_display()}"

class MonthlyBudget(models.Model):
    # 货币种类选项（可以与支出条目中的货币种类选项共用）
    CURRENCIES = [
        ('CNY', 'CNY'),
        ('USD', 'USD'),
        ('EUR', 'EUR'),
        ('JPY', 'JPY'),
        ('GBP', 'GBP'),
        ('other', 'Other'),
    ]

    year = models.IntegerField()  # 年份
    month = models.IntegerField()  # 月份 (1-12)
    total_budget = models.DecimalField(max_digits=10, decimal_places=2)  # 总预算
    currency = models.CharField(max_length=10, choices=CURRENCIES, default='CNY')  # 货币种类
    remaining_budget = models.DecimalField(max_digits=10, decimal_places=2)  # 剩余预算
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    def __str__(self):
        return f"Budget for {self.year}-{self.month}"

    def save(self, *args, **kwargs):
        # 在保存之前，确保剩余预算等于总预算
        if not self.remaining_budget:
            self.remaining_budget = self.total_budget
        super(MonthlyBudget, self).save(*args, **kwargs)

    class Meta:
        unique_together = ('year', 'month')

consumptionANDincome/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from .models import ExpenseEntry, IncomeEntry
from .forms import ExpenseEntryForm, IncomeEntryForm
from .models import IncomeEntry, ExpenseEntry
from django.db.models import Sum
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from django.utils import timezone
from datetime import datetime
from django.db import transaction

@login_required(login_url="/login/")
def index(request):
    return render(request, "index.html")

@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]
        template = loader.get_template('pages/' + load_template)
        return HttpResponse(template.render(context, request))

    except:

        template = loader.get_template( 'pages/error-404.html' )
        return HttpResponse(template.render(context, request))


# 收入统计视图
from django.shortcuts import render
from .models import IncomeEntry
from django.db.models import Sum

# def income_statistic(request):
#     # 获取当前账户的所有收入记录
#     incomes = IncomeEntry.objects.all()  # 可以根据需要修改筛选条件
    
#     # 计算总收入
#     total_income = incomes.aggregate(total=Sum('amount'))['total'] or 0
    
#     # 返回数据到模板
#     return render(request, 'consumptionANDincome/income_statistic.html', {
#         'incomes': incomes,
#         'total_income': total_income,
#     })
# # 支出统计视图



def income_statistic(request):
    # 获取当前账户的所有收入记录
    incomes = IncomeEntry.objects.all()  # 可以根据需要修改筛选条件
    
    # 计算总收入
    total_income = incomes.aggregate(total=Sum('amount'))['total'] or 0
    
    # 返回数据到模板
    return render(request, 'consumptionANDincome/income_statistic.html', {
        'incomes': incomes,
        'total_income': total_income,
    })


def consumption_statistic(request):
    # 获取当前账户的所有支出记录
    consumptions = ExpenseEntry.objects.all()  # 可以根据需要修改筛选条件
    
    # 计算总支出
    total_consumption = consumptions.aggregate(total=Sum('amount'))['total'] or 0
    
    # 返回数据到模板
    return render(request, 'consumptionANDincome/consumption_statistic.html', {
        'consumptions': consumptions,
        'total_consumption': total_consumption,
    })

# 结余统计视图

def surplus_statistic(request):
    # 获取所有收入记录
    total_income = IncomeEntry.objects.aggregate(total=Sum('amount'))['total'] or 0
    
    # 获取所有支出记录
    total_consumption = ExpenseEntry.objects.aggregate(total=Sum('amount'))['total'] or 0
    
    # 计算结余
    surplus = total_income - total_consumption
    
    # 返回数据到模板
    return render(request, 'consumptionANDincome/surplus_statistic.html', {
        'total_income': total_income,
        'total_consumption': total_consumption,
        'surplus': surplus,
    })


# 添加支出
def add_expense(request):
    if request.method == 'POST':
        form = ExpenseEntryForm(request.POST)
        if form.is_valid():
            with transaction.atomic():  # Ensure atomicity for consistency
                # Save the expense entry
                expense_entry = form.save()

                # Check if the expense should be included in the balance
                if expense_entry.include_in_balance:
                    # Retrieve the associated fund account
                    fund_account = expense_entry.account

                    # Update the account balance
                    fund_account.balance -= expense_entry.amount

                    # Save the updated balance
                    fund_account.save()

            # Redirect to the expense list page
            return redirect('consumptionANDincome:expense_list')
    else:
        form = ExpenseEntryForm()

    return render(request, 'consumptionANDincome/add_expense.html', {'form': form})

# 删除支出
def delete_expense(request, expense_id):
    try:
        expense = ExpenseEntry.objects.get(expense_id=expense_id)
        expense.delete()
    except ExpenseEntry.DoesNotExist:
        pass  # 如果没有找到对应的支出项，可以选择记录日志或其他处理

    return redirect('consumptionANDincome:expense_list')  # 删除成功后重定向到支出统计页面

# 更新支出
def update_expense(request, expense_id):
    try:
        expense = ExpenseEntry.objects.get(expense_id=expense_id)
    except ExpenseEntry.DoesNotExist:
        return redirect('consumptionANDincome:expense_list')  # 如果没有找到对应的支出项，跳转到支出统计页面

    if request.method == 'POST':
        form = ExpenseEntryForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            return redirect('consumptionANDincome:expense_list')  # 更新成功后重定向到支出统计页面
    else:
        form = ExpenseEntryForm(instance=expense)

    return render(request, 'consumptionANDincome/update_expense.html', {'form': form, 'expense': expense})

# 添加收入
def add_income(request):
    if request.method == 'POST':
        form = IncomeEntryForm(request.POST)
        if form.is_valid():
            with transaction.atomic():  # Use a transaction to ensure consistency
                # Save the income entry
                income_entry = form.save()

                # Check if the income should be included in the balance
                if income_entry.include_in_balance:
                    # Retrieve the associated fund account
                    fund_account = income_entry.account

                    # Update the account balance
                    fund_account.balance += income_entry.amount

                    # Save the updated balance
                    fund_account.save()

            # Redirect to the income list page
            return redirect('consumptionANDincome:income_list')
    else:
        form = IncomeEntryForm()

    return render(request, 'consumptionANDincome/add_income.html', {'form': form})

# 删除收入
def delete_income(request, income_id):
    try:
        income = IncomeEntry.objects.get(income_id=income_id)
        income.delete()
    except IncomeEntry.DoesNotExist:
        pass  # 如果没有找到对应的收入项，可以选择记录日志或其他处理

    return redirect('consumptionANDincome:income_list')  # 删除成功后重定向到收入统计页面

# 更新收入
def update_income(request, income_id):
    try:
        income = IncomeEntry.objects.get(income_id=income_id)
    except IncomeEntry.DoesNotExist:
        return redirect('consumptionANDincome:income_list')  # 如果没有找到对应的收入项，跳转到收入统计页面

    if request.method == 'POST':
        form = IncomeEntryForm(request.POST, instance=income)
        if form.is_valid():
            form.save()
            return redirect('consumptionANDincome:income_list')  # 更新成功后重定向到收入统计页面
    else:
        form = IncomeEntryForm(instance=income)

    return render(request, 'consumptionANDincome/update_income.html', {'form': form, 'income': income})

def expenseincome_list(request):
    # 这里编写获取和展示收支总览的逻辑
    return render(request, 'consumptionANDincome/expenseincome_list.html')

# 收入视图
def income_list(request):
    # 这里编写获取和展示收入的逻辑
    query = request.GET.get('q', '')  # 获取 'q' 参数，默认为空字符串

    # 根据 'q' 参数过滤支出记录
    if query:
        incomes = IncomeEntry.objects.filter(income_category__icontains=query)  # 'icontains' 用于不区分大小写的模糊查询
    else:
        incomes = IncomeEntry.objects.all()
    
    return render(request, 'consumptionANDincome/income_list.html',{'incomes':incomes})


# 支出视图
def expense_list(request):
    # 这里编写获取和展示支出的逻辑
    query = request.GET.get('q', '')  # 获取 'q' 参数，默认为空字符串

    # 根据 'q' 参数过滤支出记录
    if query:
        expenses = ExpenseEntry.objects.filter(expense_category__icontains=query)  # 'icontains' 用于不区分大小写的模糊查询
    else:
        expenses = ExpenseEntry.objects.all()
    
    return render(request, 'consumptionANDincome/expense_list.html',{'expenses':expenses})

@api_view(['GET'])
def weekly_expenses_by_category(request):
    # Get the start and end of the current week
    today = timezone.now()
    start_of_week = today - timezone.timedelta(days=today.weekday())  # Monday
    end_of_week = start_of_week + timezone.timedelta(days=6)  # Sunday

    # Filter expenses for the current week
    weekly_expenses = ExpenseEntry.objects.filter(
        expense_time__date__range=[start_of_week, end_of_week]
    )

    # Aggregate expenses by category
    expenses_by_category = (
        weekly_expenses.values('expense_category')
        .annotate(total_amount=Sum('amount'))
        .order_by('expense_category')
    )

    # Format the response data
    data = {
        "expenses_by_category": [
            {
                "category": expense['expense_category'],
                "total_amount": expense['total_amount']
            }
            for expense in expenses_by_category
        ]
    }
    return Response(data)

@api_view(['GET'])
def weekly_income_by_category(request):
    # Get the start and end of the current week
    today = timezone.now()
    start_of_week = today - timezone.timedelta(days=today.weekday())  # Monday
    end_of_week = start_of_week + timezone.timedelta(days=6)  # Sunday

    # Filter income for the current week
    weekly_income = IncomeEntry.objects.filter(
        income_time__date__range=[start_of_week, end_of_week]
    )

    # Aggregate income by category
    income_by_category = (
        weekly_income.values('income_category')
        .annotate(total_amount=Sum('amount'))
        .order_by('income_category')
    )

    # Format the response data
    data = {
        "income_by_category": [
            {
                "category": income['income_category'],
                "total_amount": income['total_amount']
            }

templates/consumptionANDincome/add_expense.html
{% extends 'base.html' %}
{% load static %}
{% block title %}添加支出{% endblock %}

{% block trace %}
<div class="container-fluid px-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb my-0">
            <li class="breadcrumb-item"><span>Home</span></li>
            <li class="breadcrumb-item"><span>收支</span></li>
            <li class="breadcrumb-item active"><span>添加支出</span></li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="container-lg px-4">
    <div class="card-body">
        <h2>添加支出记录</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">提交</button>
        </form>
    </div>
</div>
{% endblock %}

templates/consumptionANDincome/add_income.html
{% extends 'base.html' %}
{%load static%}
{% block title %}添加收入{% endblock %}

{% block trace %}
<div class="container-fluid px-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb my-0">
            <li class="breadcrumb-item"><span>Home</span></li>
            <li class="breadcrumb-item"><span>收支</span></li>
            <li class="breadcrumb-item active"><span>添加收入</span></li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="container-lg px-4">
    <div class="card-body">
        <h2>添加收入记录</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">提交</button>
        </form>
    </div>
</div>
{% endblock %}

templates/consumptionANDincome/consumption_statistic.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1 class="my-4">支出统计</h1>

    <!-- 支出条目列表 -->
    <table class="table table-striped">
      <thead>
        <tr>
          <th>支出类别</th>
          <th>金额</th>
          <th>货币类型</th>
          <th>支出时间</th>
          <th>账户</th>
          <th>账本</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in consumptions %}
          <tr>
            <td>{{ expense.get_expense_category_display }}</td>
            <td>{{ expense.amount }}</td>
            <td>{{ expense.get_currency_display }}</td>
            <td>{{ expense.expense_time }}</td>
            <td>{{ expense.account.name }}</td>
            <td>{{ expense.account_book.name }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="6">没有找到支出记录。</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- 显示总支出 -->
    <div class="my-4">
      <h3>总支出：{{ total_consumption }}</h3>
    </div>
  </div>
{% endblock %}

templates/consumptionANDincome/expense_list.html
{% extends 'base.html' %}
{% load static%}
{% block title %}支出{% endblock %}
{% block trace %}
<div class="container-fluid px-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb my-0">
            <li class="breadcrumb-item"><span>Home</span></li>
            <li class="breadcrumb-item"><span>收支</span></li>
            <li class="breadcrumb-item active"><span>支出</span></li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="body flex-grow-1">
    <div class="container-lg px-4">
        <!-- 按钮和搜索框放在同一行 -->
        <div class="mb-3 d-flex align-items-center">
            <a href="{% url 'consumptionANDincome:add_expense' %}" class="btn btn-primary me-2">添加支出</a>
            <form class="d-flex" method="get" action="{% url 'consumptionANDincome:expense_list' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>

        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">记录账本</th>
                        <th scope="col">支出金额</th>
                        <th scope="col">类别</th>
                        <th scope="col">日期</th>
                        <th scope="col">账户</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% if expenses %}
                        {% for expense in expenses %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ expense.account_book }}</td>
                                <td>{{ expense.amount }}</td>
                                <td>{{ expense.expense_category }}</td>
                                <td>{{ expense.expense_time }}</td>
                                <td>{{ expense.account }}</td>
                                
                                <td>
                                    <form action="{% url 'consumptionANDincome:delete_expense' expense.expense_id %}" method="post" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">删除</button>
                                    </form>
                                    <form action="{% url 'consumptionANDincome:update_expense' expense.expense_id %}" method="post" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-warning">修改</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="7">没有找到支出记录。</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/consumptionANDincome/expenseincome_list.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
  <h1>我的收支</h1>
  <p>查看你的收支详情：</p>
  <ul>
    <li><a href="{% url 'consumptionANDincome:income_list' %}">收入</a></li>
    <li><a href="{% url 'consumptionANDincome:expense_list' %}">支出</a></li>
  </ul>
{% endblock %}

templates/consumptionANDincome/income_list.html
{% extends 'base.html' %}

{% block title %}收入{% endblock %}

{% block trace %}
<div class="container-fluid px-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb my-0">
            <li class="breadcrumb-item"><span>Home</span></li>
            <li class="breadcrumb-item"><span>收支</span></li>
            <li class="breadcrumb-item active"><span>收入</span></li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="body flex-grow-1">
    <div class="container-lg px-4">
        <!-- 按钮和搜索框放在同一行 -->
        <div class="mb-3 d-flex align-items-center">
            <a href="{% url 'consumptionANDincome:add_income' %}" class="btn btn-primary me-2">添加收入</a>
            <form class="d-flex" method="get" action="{% url 'consumptionANDincome:income_list' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>

        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">记录账本</th>
                        <th scope="col">收入金额</th>
                        <th scope="col">来源</th>
                        <th scope="col">日期</th>
                        <th scope="col">账户</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% if incomes %}
                        {% for income in incomes %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ income.account_book }}</td>
                                <td>{{ income.amount }}</td>
                                <td>{{ income.income_category }}</td>
                                <td>{{ income.income_time }}</td>
                                <td>{{ income.account }}</td>
                                
                                <td>
                                    <form action="{% url 'consumptionANDincome:delete_income' income.income_id %}" method="post" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">删除</button>
                                    </form>
                                    <form action="{% url 'consumptionANDincome:update_income' income.income_id %}" method="post" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-warning">修改</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="6">没有找到收入记录。</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/consumptionANDincome/income_statistic.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1 class="my-4">收入统计</h1>

    <!-- 收入条目列表 -->
    <table class="table table-striped">
      <thead>
        <tr>
          <th>收入类别</th>
          <th>金额</th>
          <th>货币类型</th>
          <th>收入时间</th>
          <th>账户</th>
          <th>账本</th>
        </tr>
      </thead>
      <tbody>
        {% for income in incomes %}
          <tr>
            <td>{{ income.get_income_category_display }}</td>
            <td>{{ income.amount }}</td>
            <td>{{ income.get_currency_display }}</td>
            <td>{{ income.income_time }}</td>
            <td>{{ income.account.name }}</td>
            <td>{{ income.account_book.name }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="6">没有找到收入记录。</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- 显示总收入 -->
    <div class="my-4">
      <h3>总收入：{{ total_income }}</h3>
    </div>
  </div>
{% endblock %}

templates/consumptionANDincome/update_expense.html
{% extends 'base.html' %}
{% load static %}
{% block title %}更新支出{% endblock %}

{% block trace %}
<div class="container-fluid px-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb my-0">
            <li class="breadcrumb-item"><span>Home</span></li>
            <li class="breadcrumb-item"><span>收支</span></li>
            <li class="breadcrumb-item active"><span>更新支出</span></li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="container-lg px-4">
    <div class="card-body">
        <h2>更新支出记录</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">提交更新</button>
        </form>
    </div>
</div>
{% endblock %}

templates/consumptionANDincome/update_income.html
{% extends 'base.html' %}
{% load static %}
{% block title %}更新收入{% endblock %}

{% block trace %}
<div class="container-fluid px-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb my-0">
            <li class="breadcrumb-item"><span>Home</span></li>
            <li class="breadcrumb-item"><span>收支</span></li>
            <li class="breadcrumb-item active"><span>更新收入</span></li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="container-lg px-4">
    <div class="card-body">
        <h2>更新收入记录</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">提交更新</button>
        </form>
    </div>
</div>
{% endblock %}